<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dev-pan" ignored="0" name="PCS1" tests="1" failures="1" timestamp="12 Oct 2017 15:52:21 GMT" time="34.106" errors="0">
  <testcase name="enroll" time="34.09" classname="getmycourse.CourseEnrol">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at getmycourse.CourseEnrol.enroll(CourseEnrol.java:43)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- enroll -->
</testsuite> <!-- PCS1 -->
